# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Instance": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://vitojph.github.io/testing43/"

git_url = "https://github.com/vitojph/testing43/tree/master/"

def custom_doc_links(name): return None
