# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['Instance']

# Cell
import numpy as np

from dataclasses import dataclass
from typing import List


@dataclass
class Instance:
    """An Instance is a sample from a dataset."""

    text: str
    tokens: List[str] = None
    vectors: np.ndarray = None
    embedding: np.ndarray = None

    def __repr__(self):
        if self.tokens:
            return f"{' '.join(self.tokens[:25])}"
        else:
            return self.text[:25]